// Part of DvtkScriptSupport.dll - .NET script engine that runs MS-script based DICOM test scripts
// Copyright © 2001-2005
// Philips Medical Systems NL B.V., Agfa-Gevaert N.V.

using System;

namespace DvtkScriptSupport
{
    /// <summary>
    /// Interface provided by the script host.
    /// </summary>
    public interface IScriptHost
    {
        /// <summary>
        /// Source code of the executed script.
        /// </summary>
        string SourceCode { get; set; }
        /// <summary>
        /// Language of the script source and the engine used to execute this code
        /// </summary>
        string Language { get; }

        /// <summary>
        /// Occurs when a compile error report is generated by the vsa engine.
        /// </summary>
        event CompilerErrorEventHandler CompilerErrorEvent;

        /// <summary>
        /// Add an event source to the script context.
        /// </summary>
        /// <param name="Name">The name of the event source within the script context.</param>
        /// <param name="Instance">The instance of the event source handed to the script context.</param>
        /// <returns>Success</returns>
        bool AddEventSource(        
            string eventSourceName,
            object Instance);

        /// <summary>
        /// Add a reference to the script context.
        /// This allows the use of assemblies from within the script context.
        /// </summary>
        /// <param name="Name">The name of the reference within the script engine.</param>
        /// <param name="AssemblyName">The fullname of the referenced assembly.</param>
        /// <returns>Success</returns>
        bool AddReference(
            string Name,
            string AssemblyName);

        /// <summary>
        /// Add an <see cref="object"/> <c>instance</c> to the script environment.
        /// The <c>instance</c> may be addressed from within a script by means
        /// of the <c>name</c>.
        /// </summary>
        /// <param name="name">global variable name to be used from within a script.</param>
        /// <param name="instance">instance that may be addressed from within a script.</param>
        /// <returns>Success</returns>
        bool AddGlobalInstance(
            string name, 
            object instance);

        /// <summary>
        /// Remove a global instance within the <c>name</c> from the script environment.
        /// </summary>
        /// <param name="name">global variable name to be used from within a script.</param>
        /// <returns>Success</returns>
        bool RemoveGlobalInstance(
            string name);

        /// <summary>
        /// Compile the source code within the script context that is set up.
        /// </summary>
        /// <returns>Success code</returns>
        bool Compile();

        /// <summary>
        /// Execute the method which is defined in the script by the moduleName and the methodName.
        /// </summary>
        /// <remarks>
        /// The method needs to be a static method!
        /// </remarks>
        /// <param name="ModuleName">for instance <c>module DvScript ... end module</c></param>
        /// <param name="MethodName">for instance <c>sub Main() .... end sub</c></param>
        /// <param name="Arguments"></param>
        /// <returns></returns>
        object Invoke(
            string ModuleName,
            string MethodName,
            object[] Arguments);
    }

    public abstract class VsaScriptHost
        : IScriptHost
    {
        /// <summary>
        /// Engine to be used in the class
        /// </summary>
        private Microsoft.Vsa.IVsaEngine _VsaEngine;
        
        /// <summary>
        /// Code Item that stores the script
        /// </summary>
        private Microsoft.Vsa.IVsaCodeItem _VsaCodeItem;

        /// <summary>
        /// The implementation of the VSASite used for call backs
        /// </summary>
        private VsaSite _VsaSite;

        /// <summary>
        /// Language of the script source and the engine used to execute this code
        /// </summary>
        public string Language
        {
            get { return this._Language; }
        }
        private string _Language;

        /// <summary>
        /// Source code of the executed script.
        /// </summary>
        public string SourceCode
        {
            get
            {
                return this._VsaCodeItem.SourceText;
            }
            set
            {
                //
                // Fix for Microsoft bug:
                // {'\n','\r'} are automatically appended to the
                // Microsoft.Vsa.IVsaCodeItem during setting of property SourceText.
                // This cause unexpected linefeeds in the code.
                //
                // Workaround:
                // If value ends with {'\n','\r'} chars, remove {'\n','\r'} chars
                // before assignment to SourceText property.
                //
                if (value != null) value = value.TrimEnd('\n','\r');
                //
                this._VsaCodeItem.SourceText = value;
            }
        }

        internal VsaScriptHost(
            string language,
            string moniker,
            string nameSpace)
        {
            if (language == null) throw new System.ArgumentNullException();
            if (moniker == null) throw new System.ArgumentNullException();
            if (nameSpace == null) throw new System.ArgumentNullException();

            try
            {
                // Store the language
                this._Language = language;
                // Create the Script Engine based on the language
                _CreateEngine();
                // The moniker, or root moniker, 
                // is the unique name by which a script engine is identified
                // Set the moniker to be something relatively unique
                this._VsaEngine.RootMoniker = moniker;
                // Create a new instance of the VSA Site
                this._VsaSite = new VsaSite();
                this._VsaSite.CompilerErrorEvent +=new CompilerErrorEventHandler(_VsaSite_CompilerErrorEvent);
                // Get the instance of the site 
                this._VsaEngine.Site = this._VsaSite;
                // Initialize the engine
                this._VsaEngine.InitNew();
                // Set the rootnamespace
                this._VsaEngine.RootNamespace = nameSpace;
                // Set the engine (display) name
                this._VsaEngine.Name = this._VsaEngine.RootNamespace;
            }
            catch (Microsoft.Vsa.VsaException e)
            {
                throw new System.ApplicationException(
                    string.Format(
                    (
                    "A VsaException occurred\n" +
                    "ErrorCode {0}\n"
                    ),  
                    e.ErrorCode.ToString()
                    )
                    );
            }
            try
            {
                // Create a blank codeItem
                if (this.Language == "JScript.NET")
                {
                    this._VsaCodeItem = 
                        (Microsoft.Vsa.IVsaCodeItem)
                        this._VsaEngine.Items.CreateItem(
                        "ScriptCode",
                        Microsoft.Vsa.VsaItemType.Code,
                        Microsoft.Vsa.VsaItemFlag.Module);
                }
                else
                {
                    this._VsaCodeItem = 
                        (Microsoft.Vsa.IVsaCodeItem)
                        this._VsaEngine.Items.CreateItem(
                        "ScriptCode",
                        Microsoft.Vsa.VsaItemType.Code,
                        Microsoft.Vsa.VsaItemFlag.None);
                }
            }
            catch (Microsoft.Vsa.VsaException e)
            {
                throw new System.ApplicationException(
                    string.Format(
                    (
                    "A VsaException occurred\n" +
                    "ErrorCode {0}\n"
                    ),  
                    e.ErrorCode.ToString()
                    )
                    );
            }
            // Create a reference to system
            this.AddReference("System", "System.dll");
            // Create a reference to Windows
            this.AddReference("Forms", "System.Windows.Forms.dll");
            // Add an import to system
            this._AddImport("System");
            // Add an import to system
            this._AddImport("System.Windows.Forms");
        }

        /// <summary>
        /// Add an <see cref="object"/> <c>instance</c> to the script environment.
        /// The <c>instance</c> may be addressed from within a script by means
        /// of the <c>name</c>.
        /// </summary>
        /// <param name="name">global variable name to be used from within a script.</param>
        /// <param name="instance">instance that may be addressed from within a script.</param>
        /// <returns>Success</returns>
        public bool AddGlobalInstance(string name, object instance)
        {
            if (name == null) throw new System.ArgumentNullException();
            if (instance == null) throw new System.ArgumentNullException();

            if (!this._VsaEngine.IsValidIdentifier(name)) return false;

            try
            {
                //
                // Remove old VsaGlobalItem from engine and site.
                //
                this.RemoveGlobalInstance(name);
                //
                // Add new VsaGlobalItem to engine and site.
                //
                this._VsaSite.AddGlobalInstance(name, instance);
                Microsoft.Vsa.IVsaGlobalItem vsaGlobalItem =
                    (Microsoft.Vsa.IVsaGlobalItem)
                    this._VsaEngine.Items.CreateItem(
                    name, 
                    Microsoft.Vsa.VsaItemType.AppGlobal, 
                    Microsoft.Vsa.VsaItemFlag.None);
                vsaGlobalItem.TypeString = instance.GetType().ToString();
            }
            catch (Microsoft.Vsa.VsaException e)
            {
                throw new System.ApplicationException(
                    string.Format(
                    (
                    "A VsaException occurred\n" +
                    "ErrorCode {0}\n"
                    ),  
                    e.ErrorCode.ToString()
                    )
                    );
            }
            return true;
        }

        /// <summary>
        /// Remove a global instance within the <c>name</c> from the script environment.
        /// </summary>
        /// <param name="name">global variable name to be used from within a script.</param>
        /// <returns>Success</returns>
        public bool RemoveGlobalInstance(string name)
        {
            if (name == null) throw new System.ArgumentNullException();

            bool success = false;

            try
            {
                //
                // remove existing VsaGlobalItem from engine and site
                //
                if (this._VsaSite.GetGlobalInstance(name) != null)
                {
                    this._VsaEngine.Items.Remove(name);
                    this._VsaSite.RemoveGlobalInstance(name);
                    success = true;
                }
                else
                {
                    success = false;
                }
            }
            catch (Microsoft.Vsa.VsaException e)
            {
                throw new System.ApplicationException(
                    string.Format(
                    (
                    "A VsaException occurred\n" +
                    "ErrorCode {0}\n"
                    ),  
                    e.ErrorCode.ToString()
                    )
                    );
            }
            return success;
        }

        /// <summary>
        /// Add an event source to the script context.
        /// </summary>
        /// <param name="Name">The name of the event source within the script context.</param>
        /// <param name="Instance">The instance of the event source handed to the script context.</param>
        /// <returns>Success</returns>
        public bool AddEventSource(
            string eventSourceName, object instance)
        {
            if (eventSourceName == null) throw new System.ArgumentNullException();
            if (instance == null) throw new System.ArgumentNullException();

            if (!this._VsaEngine.IsValidIdentifier(eventSourceName)) return false;

            string eventSourceType = instance.GetType().ToString();
            string assemblyName = instance.GetType().Assembly.FullName;
            //
            // Add an event source to the engine
            //
            this._VsaCodeItem.AddEventSource(eventSourceName, eventSourceType);
            //
            // Add the instance to the sites hashtable
            //
            this._VsaSite.AddEvent(eventSourceName, instance);
            //
            // JScript.NET Beta 2 has a bug whereby adding an event source actually
            // adds an entry to the item list so adding "Ref" to the Name ensure that
            // theres no naming collisions
            //
            this.AddReference(eventSourceName + "Ref", assemblyName);
            //
            // Make sure the reference gets imported
            // Use split to get the type from the beginning of the Type String
            //
            this._AddImport(instance.GetType().Namespace);

            return true;
        }

        /// <summary>
        /// Add a reference to the script context.
        /// This allows the use of assemblies from within the script context.
        /// </summary>
        /// <param name="Name">The name of the reference within the script engine.</param>
        /// <param name="AssemblyName">The fullname of the referenced assembly.</param>
        /// <returns>Success</returns>
        public bool AddReference(string referenceItemName, string assemblyName)
        {
            if (referenceItemName == null) throw new System.ArgumentNullException();
            if (assemblyName == null) throw new System.ArgumentNullException();

            if (!this._VsaEngine.IsValidIdentifier(referenceItemName)) return false;

            try
            {
                //
                // Create a reference to the object
                //
                Microsoft.Vsa.IVsaReferenceItem 
                    vsaReferenceItem =
                    (Microsoft.Vsa.IVsaReferenceItem)
                    this._VsaEngine.Items.CreateItem(
                    referenceItemName,
                    Microsoft.Vsa.VsaItemType.Reference,
                    Microsoft.Vsa.VsaItemFlag.None);
                //
                // Set the assemblyname
                //
                vsaReferenceItem.AssemblyName = assemblyName;
            }
            catch (Microsoft.Vsa.VsaException e)
            {
                throw new System.ApplicationException(
                    string.Format(
                    (
                    "A VsaException occurred\n" +
                    "ErrorCode {0}\n"
                    ),  
                    e.ErrorCode.ToString()
                    )
                    );
            }
            return true;
        }

        /// <summary>
        /// Compile the source code within the script context that is set up.
        /// </summary>
        /// <returns>Success code</returns>
        public bool Compile()
        {
            bool compileSuccess = true;
            try
            {
                // Check to see if the engine is running
                if (this._VsaEngine.IsRunning) 
                {
                    // If it is reset the engine
                    this._VsaEngine.Reset();
                    this._VsaEngine.RevokeCache();
                }
                if (compileSuccess) compileSuccess = this._VsaEngine.Compile();
                if (compileSuccess) this._VsaEngine.Run();
            }
            catch (Microsoft.Vsa.VsaException e)
            {
                throw new System.ApplicationException(
                    string.Format(
                    (
                    "A VsaException occurred\n" +
                    "ErrorCode {0}\n"
                    ),  
                    e.ErrorCode.ToString()
                    )
                    );
            }
            return compileSuccess;
        }

        /// <summary>
        /// Execute the method which is defined in the script by the moduleName and the methodName.
        /// </summary>
        /// <remarks>
        /// The method needs to be a static method!
        /// </remarks>
        /// <param name="ModuleName">for instance <c>module DvScript ... end module</c></param>
        /// <param name="MethodName">for instance <c>sub Main() .... end sub</c></param>
        /// <param name="Arguments"></param>
        /// <returns></returns>
        public object Invoke(string moduleName, string methodName, object[] arguments)
        {
            if (moduleName == null) throw new System.ArgumentNullException();
            if (methodName == null) throw new System.ArgumentNullException();

            //
            // Engine must be running in order to use reflection to determine
            // provided methods by the Vsa script environment at the run-time.
            //
            if (!this._VsaEngine.IsRunning)
            {
                throw new Exception("Engine isn't running!");
            }
            //
            // Create the fullname of the namespace that contains the method
            //
            string fullName = this._VsaEngine.RootNamespace + "." + moduleName;
            System.Type moduleType = null;
            try
            {
                //
                // Get the module type from the assembly
                //
                moduleType = this._VsaEngine.Assembly.GetType(fullName, true, true);
            }
            catch (Microsoft.Vsa.VsaException e)
            {
                throw new System.ApplicationException(
                    string.Format(
                    (
                    "A VsaException occurred\n" +
                    "ErrorCode {0}\n"
                    ),  
                    e.ErrorCode.ToString()
                    )
                    );
            }
            //
            // Get the method from the type
            //
            System.Reflection.MethodInfo methodInfo = moduleType.GetMethod(methodName);
            // Check to see if we can find the method
            if (methodInfo == null) 
            {
                throw new Exception("method not found");
            }
            //
            // Call the method with the arguments and return any value.
            // Note: 
            // Invoke is called with argument 'object obj' == null;
            // this means a static call is made!
            //
            return methodInfo.Invoke(null, arguments);
        }

        private void _CreateEngine()
        {
            switch (this.Language)
            {
                case "VB":
                case "Visual Basic":
                    this._VsaEngine = new Microsoft.VisualBasic.Vsa.VsaEngine();
                    break;
                case "JScript":
                case "JScript.NET":
                    this._VsaEngine = new Microsoft.JScript.Vsa.VsaEngine();
                    break;
                default:
                    throw new Exception("Unknown Engine");
            }                    
        }

        internal protected void _AddImport(string nameSpace)
        {
            if (nameSpace == null) throw new System.ArgumentNullException();

            string importStatement;
            // Should use CodeDOM here really
            // That will be in the next installment
            if (this.Language == "VB")
            {
                importStatement = "imports";
            }
            else
            {
                importStatement = "import";
            }
            importStatement += " " + nameSpace + "\n";
            // Add the imports to the beginning of the script
            this.SourceCode = string.Concat(importStatement, this.SourceCode);
        }

        #region Events Sources (Publishers)
        /// <summary>
        /// Occurs when a compile error report is generated by the vsa engine.
        /// </summary>
        public event CompilerErrorEventHandler CompilerErrorEvent;
        #endregion

        /// <summary>
        /// Cascade the event from the vsa site to external listeners.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void _VsaSite_CompilerErrorEvent(object sender, CompilerErrorEventArgs e)
        {
            //
            // Invoke the delegates
            //
            if (CompilerErrorEvent != null) CompilerErrorEvent(this, e);
        }
    }
}
